export const seedData = {
  products: [
    {
      id: 'product-ao-thun',
      name: 'Áo thun cotton cao cấp',
      sku: 'AT-CT-001',
      totalImported: 420,
      totalExported: 0,
      factoryReturnDefects: 12,
      unfixableDefects: 6,
      fixableDefects: 18,
      lowStockThreshold: 80,
    },
    {
      id: 'product-quan-jean',
      name: 'Quần jean nam dáng slim',
      sku: 'QJ-SL-002',
      totalImported: 260,
      totalExported: 0,
      factoryReturnDefects: 4,
      unfixableDefects: 3,
      fixableDefects: 9,
      lowStockThreshold: 45,
    },
    {
      id: 'product-giay',
      name: 'Giày thể thao nữ',
      sku: 'GT-N-003',
      totalImported: 180,
      totalExported: 0,
      factoryReturnDefects: 2,
      unfixableDefects: 4,
      fixableDefects: 5,
      lowStockThreshold: 35,
    },
  ],
  shops: [
    { id: 'shop-ha-noi', name: 'Cửa hàng Hà Nội', address: 'Quận Cầu Giấy, Hà Nội', manager: 'Nguyễn Minh Anh' },
    { id: 'shop-da-nang', name: 'Cửa hàng Đà Nẵng', address: 'Quận Hải Châu, Đà Nẵng', manager: 'Trần Quốc Bảo' },
    { id: 'shop-sai-gon', name: 'Cửa hàng Sài Gòn', address: 'Quận 1, TP. Hồ Chí Minh', manager: 'Lê Thảo Vy' },
  ],
  distributions: [
    { id: 'dist-1', productId: 'product-ao-thun', shopId: 'shop-ha-noi', quantity: 120 },
    { id: 'dist-2', productId: 'product-ao-thun', shopId: 'shop-sai-gon', quantity: 100 },
    { id: 'dist-3', productId: 'product-quan-jean', shopId: 'shop-da-nang', quantity: 70 },
    { id: 'dist-4', productId: 'product-giay', shopId: 'shop-sai-gon', quantity: 45 },
  ],
  users: [
    {
      id: 'user-admin',
      name: 'admin',
      email: 'admin@khoviet.local',
      role: 'admin',
      active: true,
      permissions: 'system:admin,inventory:read,inventory:write,shop:manage,user:manage,log:read',
      passwordHash: 'pbkdf2$admin-salt$15d84674c6c289950b31abf1621b55a9f685f5a2d5703bb0b43b5f65b3c99ccb',
    },
    {
      id: 'user-staff',
      name: 'nv',
      email: 'nhanvien@khoviet.local',
      role: 'staff',
      active: true,
      permissions: 'inventory:import,inventory:export',
      passwordHash: 'pbkdf2$staff-salt$aecc434cf6d28ec2a11f4c7ef878586338f07e88c17845e34af5560d15cd7ea3',
    },
  ],
  activityLogs: [
    {
      id: 'log-1',
      action: 'Khởi tạo hệ thống',
      description: 'Tạo dữ liệu tồn kho ban đầu cho nhiều cửa hàng.',
      userId: 'user-admin',
      userName: 'admin',
      createdAt: new Date().toISOString(),
    },
  ],
};

